# Función Copy

Cuando queremos trabajar con pedazos de arreglos, generalmente hacemos una nueva variable y asignamos ese pedazo a nuestra nueva variable, pero !Oh, sorpresa¡, al hacer modificaciones a nuestro trozo nos dimos cuenta que se ha modificado el arreglo original.
La función copy viene a salvarnos de estas situaciones :D. 

In [2]:
import numpy as np

Declararemos un arreglo de numpy y haremos slicing para asignar un trozo del arreglo a una variable llamada trozo

In [3]:
arr =np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
trozo = arr[0:6]
trozo

array([0, 1, 2, 3, 4, 5])

Modificaremos nuestro trozo

In [6]:
trozo[:] = 0 
trozo

array([0, 0, 0, 0, 0, 0])

Ahora veamos nuestro arreglo original

In [7]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Como se habia mencionado, modificamos nuestro arreglo original sin querer, ahora veamos la solución.

Haremos una variable llamda cpy y aplicaremos la funcion .copy() de nuestro arreglo de numpy.

In [9]:
cpy = arr.copy()
cpy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Ahora modifiquemos nuestro cpy

In [11]:
cpy[:] = 100
cpy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

Veamos nuestro arreglo original

In [12]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Como vemos, no se ha modificado el arreglo con el cambio de 100 que realizamos a cpy, con excepcion de la modificación a nuestro trozo.