# Funciones frecuentemente utilizadas en numpy

Primero definamos nuestros datos a manipular

In [1]:
import numpy as np

In [9]:
arr = np.random.randint(1, 20, 10)
arr

array([14,  3,  6, 16,  8, 15, 13,  8,  9,  2])

In [10]:
matrix = arr.reshape(2, 5)
matrix

array([[14,  3,  6, 16,  8],
       [15, 13,  8,  9,  2]])

## Max, Min y ArgMax, ArgMin
- Arreglos unidimensionales:

Devuelve el maximo o minimo elemento del arreglo unidimensional

In [16]:
arr.max()

16

In [17]:
arr.min()

2

- Matrizes de n dimensiones:

Como se habia mencionado, la funcion max/min devuelve el maximo o minimo elemento de una colección; sin embargo en una matriz de varias dimensiones, no solo nos retornara el maximo de la colección, sino los maximos y minimos de la dimensión que vamos a consultar. 

En nuestro caso de ejemplo, vamos a consutar los maximos de la dimension del eje i y j de la matriz (diemsion 0 y 1 respectivamente)

In [12]:
matrix.max(0)

array([15, 13,  8, 16,  8])

In [13]:
matrix.max(1)

array([16, 15])

In [18]:
matrix.min(0)

array([14,  3,  6,  9,  2])

In [19]:
matrix.min(1)

array([3, 2])

Las funciones arg permiten encontrar los indices de los valores pequeños o grandes

In [65]:
matrix.argmax(0)

array([1, 1, 1, 0, 0], dtype=int64)

In [67]:
matrix.argmin(1)

array([1, 4], dtype=int64)

Una función que tambien cabe destacar es la función pico a pico (peak to peak), que permite calcular la diferencia de valor entre el valor mas grande y mas pequeño

In [69]:
#valor mas grande 16, valor mas pequeño 2
#16 - 2 = 4
arr.ptp()

14

## Funciones estadisticas

En este apartado vamos a destacar las funciones principales mas usadas para obtener estadisticas basicas de la información en nuestros arreglos y matrices.

Calculae percentil (dividir el arreglo en secciones)

In [20]:
np.percentile(arr, 50)

8.5

En el percentil 50 nos dara el valor de la mitad. Lo podemos apreciar mejor si lo ordenamos y analizamos el valore de la mitad.

In [22]:
np.sort(arr)

array([ 2,  3,  6,  8,  8,  9, 13, 14, 15, 16])

Seria el mismo valor que la mediana

In [23]:
np.median(arr)

8.5

En matrizes, la funcion median nos da la mediana por ejes, mostremos las medianas del eje i

In [24]:
np.median(matrix, 0)

array([14.5,  8. ,  7. , 12.5,  5. ])

Tambien calculamos la desviación estandard

In [25]:
np.std(arr)

4.694677837722201

Varianza muestral

In [26]:
np.var(arr)

22.040000000000003

Media

In [27]:
np.mean(arr)

9.4

## Funcion concatenate

La funcion concatenate se encarga de insertar dos colecciones en una nueva colección

In [59]:
a = np.array([[1,2], [2,4]])
b = np.array([5,6])

Muy importante que las matrizes o arreglos a concatenar tengan la misma dimensión

In [60]:
b = np.expand_dims(b, axis=0)
b.ndim
b


array([[5, 6]])

In [61]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [2, 4],
       [5, 6]])

Ahora vamos a concatenar por el eje j

Muy importante, debemos sacar la matriz traspuesta, pues la matriz a concatenar debe ser de forma columnar para hacer la concatenación de la forma columnar.
Aunque también se puede optar por un reshape.

In [62]:
b = b.T
b

array([[5],
       [6]])

In [63]:
np.concatenate((a,b), axis = 1)

array([[1, 2, 5],
       [2, 4, 6]])