# Funciones frecuentemente utilizadas en numpy

Primero definamos nuestros datos a manipular

In [1]:
import numpy as np

In [9]:
arr = np.random.randint(1, 20, 10)
arr

array([14,  3,  6, 16,  8, 15, 13,  8,  9,  2])

In [10]:
matrix = arr.reshape(2, 5)
matrix

array([[14,  3,  6, 16,  8],
       [15, 13,  8,  9,  2]])

## Max
- Arreglos unidimensionales:

Devuelve el maximo elemento del arreglo unidimensional

In [11]:
arr.max()

16

- Matrizes de n dimensiones:

Como se habia mencionado, la funcion max devuelve el maximo elemento de una colección; sin embargo en una matriz de varias dimensiones, la funcion max no solo nos retornara el maximo de la colección, sino los maximos de la dimensión que vamos a consultar. 

In [12]:
matrix.max(0)

array([15, 13,  8, 16,  8])